services:
  glue:
    container_name: ${PROJECT_NAME}_container
    build:
      context: .
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}:glue-${GLUE_VERSION}
    environment:
      - AWS_REGION=${AWS_REGION}
      - GLUE_VERSION=${GLUE_VERSION}
      - PYTHONPATH=${WORKDIR}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    volumes:
      - ${ETL_PATH}/${DOMAIN}/${REPOSITORY}:${WORKDIR}
    #  - ${AWS_CREDENTIALS}:/home/glue_user/.aws
    working_dir: ${WORKDIR}
    stdin_open: true
    tty: true
    restart: unless-stopped
    # Mantener el contenedor vivo para desarrollo
